### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by joelcuevas** [VetonMuhaxhiri/Laravel-find-missing-translations#2]
Hey, just looking at your command. Great work! Have you thought about making it a Composer package so we could just add it as a dep?

**Comment by VetonMuhaxhiri** [comment]
Yes I'll take a look at it .

**Comment by lptn** [comment]
I already created it with some improvements:
 - GitHub https://github.com/diglabby/laravel-find-missing-translations
 - packagist https://packagist.org/packages/diglabby/laravel-find-missing-translations

**Comment by VetonMuhaxhiri** [comment]
Hi I've make it as **composer package**.
You can use :
`composer require veton-muhaxhiri/laravel-command-to-find-missing-translations`
